apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "helm-chart.labels" . | nindent 4 }}
